In [2]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
x[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [6]:
x[1,1:3]

array([7, 8])

In [7]:
x[1:3]

array([[ 6,  7,  8,  9, 10]])

In [14]:
x=np.array(range(15),int).reshape(3,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [31]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [65]:
print(np)

<module 'numpy' from 'D:\\build\\miniconda\\envs\\mire001\\lib\\site-packages\\numpy\\__init__.py'>


In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [4]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [41]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [43]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [44]:
np.empty(shape=(2,4), dtype=np.float32)

array([[-8.5893004e-38,  5.7453237e-43,  0.0000000e+00,  7.8061461e-39],
       [ 1.3620621e-42,  0.0000000e+00,  1.0761972e-42,  5.7453237e-43]],
      dtype=float32)

In [6]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
np.ones_like(x)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [60]:
np.zeros_like(x)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
np.eye(N=3,M=5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.diag(matrix)

array([0, 4, 8])

In [18]:
np.diag(matrix,k=-1)

array([3, 7])

In [19]:
np.random.uniform(0,5,10)

array([3.87315745, 0.0520101 , 2.98110751, 1.11346241, 3.67592158,
       4.10812272, 1.17677349, 0.71993099, 1.48663992, 1.65061085])

In [20]:
np.random.normal(0,2,10)

array([ 2.20529312, -1.7108365 ,  2.16945177, -1.25188768,  1.42756842,
       -0.01125208,  2.16280262, -1.24861562, -2.48242735,  1.33314629])

In [21]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [23]:
test_array.sum(axis=1)

array([10, 26, 42])

In [24]:
test_array = np.arange(1,13).reshape(3,4)
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [25]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [27]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [28]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [29]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [31]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [32]:
test_array.std()

3.452052529534663

In [33]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [34]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [36]:
v1=np.array([1,2,3])
v2=np.array([4,5,6])
np.vstack((v1,v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [48]:
v1=v1.reshape(-1,1)
v2=v2.reshape(-1,1)
v1

array([[1],
       [2],
       [3]])

In [40]:
v2

array([[4],
       [5],
       [6]])

In [42]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [54]:
v1=np.array([[1,2,3]])
v2=np.array([[4,5,6]])
np.concatenate((v1,v2),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
v1=np.array([1,2,3,4]).reshape(2,2)
v2=np.array([[5,6]]).reshape(2,1)
v1

array([[1, 2],
       [3, 4]])

In [59]:
v2

array([[5],
       [6]])

In [60]:
np.concatenate((v1,v2),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [61]:
v1=np.array([1,2,3,4]).reshape(2,2)
v2=np.array([[5,6]])
v1

array([[1, 2],
       [3, 4]])

In [62]:
v2

array([[5, 6]])

In [63]:
np.concatenate((v1,v2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [64]:
x=np.arange(1,7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
x+x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [66]:
x-x

array([[0, 0, 0],
       [0, 0, 0]])

In [67]:
x/x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
x**x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [69]:
x*x

array([[ 1,  4,  9],
       [16, 25, 36]])

In [70]:
x_1=np.arange(1,7).reshape(2,3)
x_2=np.arange(1,7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [72]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [73]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
x+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [75]:
x-2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [76]:
x//3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]], dtype=int32)

In [77]:
x**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [79]:
x=np.arange(1,13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
v=np.arange(10,40,10)
v

array([10, 20, 30])

In [82]:
x+v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [86]:
import numpy as np
x=np.array([4,3,2,6,8,5])
x>3

array([ True, False, False,  True,  True,  True])

In [88]:
x=np.array([1,3,0])
y=np.array([2,1,7])
x>y

array([False,  True, False])

In [89]:
x=np.array([4,7,6,3,2])
(x>3)

array([ True,  True,  True, False, False])

In [90]:
(x>3).all()

False

In [91]:
(x>3).any()

True

In [92]:
x=np.array([4,7,6,3,2])
x>5

array([False,  True,  True, False, False])

In [93]:
np.where(x>5)

(array([1, 2], dtype=int64),)

In [94]:
x=np.array([4,7,6,3,2])
np.where(x>5,10,20)

array([20, 10, 10, 20, 20])

In [95]:
x=np.array([4,7,6,3,2])
np.argsort(x)

array([4, 3, 0, 2, 1], dtype=int64)

In [96]:
np.argmax(x)

1

In [97]:
np.argmin(x)

4

In [98]:
x=np.array([4,7,6,3,2])
x>3

array([ True,  True,  True, False, False])

In [99]:
cond=x>3
x[cond]

array([4, 7, 6])

In [100]:
x.shape

(5,)

In [101]:
cond.shape

(5,)

In [102]:
x=np.array([4,7,6,3,2])
cond=np.array([1,2,0,2,2,2,],int)
x[cond]

array([7, 6, 4, 6, 6, 6])

In [103]:
x.take(cond)

array([7, 6, 4, 6, 6, 6])

In [104]:
x=np.array([[1,4],[9,16]],int)
a=np.array([0,1,1,1,0,0],int)
b=np.array([0,0,0,1,1,1],int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])