In [15]:
import numpy as np
test_array = np.array([1,4,5,8],float)
test_array

array([1., 4., 5., 8.])

In [3]:
test_array[3]

8.0

In [4]:
type(test_array[3])

numpy.float64

In [19]:
test_array=np.array([1,4,5,"8"],float)
print(test_array)

[1. 4. 5. 8.]


In [6]:
print(test_array.dtype)

float64


In [7]:
print(test_array.shape)

(4,)


In [9]:
matrix = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [21]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.array([[1,2,3.5],[4,5,6.5]],dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [24]:
x=np.array([[1,2,5,8],[1,2,5,8],[1,2,5,8]])
x.shape

(3, 4)

In [28]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8, 1, 2, 5, 8])

In [30]:
x.reshape(4,3)

array([[1, 2, 5],
       [8, 1, 2],
       [5, 8, 1],
       [2, 5, 8]])

In [34]:
x=np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
x=np.array([[1,2,3],[4,5,6]],int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
x[0][1]

2

In [39]:
x[1,2]

6

In [40]:
x[0,0]=100
x

array([[100,   2,   3],
       [  4,   5,   6]])

In [3]:
number1=[3]
number2=[3,17,1,39,8,41,2,32,99,2]
number3=[22,8,5,123,7,2,63,7,3,46]

for number in number2
    if number2 % 2 = 1:
    sum

SyntaxError: invalid syntax (3807025845.py, line 5)

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
x=np.arange(6,10).reshape(2,2)

NameError: name 'np' is not defined